services:
  app:
    image: ${CONTAINER_REGISTRY_BASE}/app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      # HTTP
      - target: 8080
        published: 8081
        protocol: tcp
    environment:
      - DATABASE_URL=host=database user=api_commercial_info password=api_commercial_info dbname=api_commercial_info port=5432
      - DATABASE_TYPE=postgres
      - ENV=prod
      - CORS_ALLOW_ORIGIN=localhost:8081,localhost:8080