services:
  app:
    image: ${CONTAINER_REGISTRY_BASE}/app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      # HTTP
      - target: 8080
        published: 8081
        protocol: tcp
    environment:
      - DATABASE_URL=host=database user=api_commercial_info password=api_commercial_info dbname=api_commercial_info port=5432
      - DATABASE_TYPE=postgres
      - ENV=prod
      - CORS_ALLOW_ORIGIN=localhost:8081,localhost:8080
    depends_on:
      - database

  database:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=api_commercial_info
      - POSTGRES_USER=api_commercial_info
      - POSTGRES_PASSWORD=api_commercial_info
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

volumes:
  db_data:
