services:
  app:
    image: ${CONTAINER_REGISTRY_BASE}/app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      # HTTP
      - target: 8080
        published: 8080
        protocol: tcp
    depends_on:
      - database