# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  up:
    desc: 'Run docker containers.'
    cmds:
      - docker compose -f compose.override.yml up -d --remove-orphans
  down:
    desc: 'Stop docker containers.'
    cmds:
      - docker-compose down
  restart:
    desc: 'Relaunch docker containers.'
    cmds:
      - task: down
      - task: up
  run:
    cmds:
      - go run .
  tidy:
    cmds:
      - go mod tidy
  build:
    cmds:
      - go build
  doc:
    cmds:
      - swag init --parseDependency --parseInternal
  fixtures:
    cmds:
      - go run . fixtures
  dump:
    cmds:
      - go run . dump
  test:
    cmds:
      - GIN_MODE=test go test .

