database:
    default:
        adapter: postgres
        encoding: utf8
        dsn: env("POSTGRES_DSN")
        pool: 5
        timeout: 5000
        config:
            log_level: silent
            #skip_default_transaction: true
            #disable_nested_transaction: true
            #create_batch_size: 5000
            #full_save_associations: true

    crm:
        adapter: sqlsrv
        encoding: utf8
        dsn: env("SQL_SERVER_DSN")
        pool: 5
        timeout: 5000