name: build and test

on:
  push:
    branches:
      - release
      - main
      - feat/ci

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker build images
        run: docker-compose -f docker-compose.yml build --no-cache

      - name: Run App
        run: |
          docker-compose -f docker-compose.yml up  -d
          docker-compose ps