name: build and test

on:
  push:
    branches:
      - release
      - main
      - feat/ci

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker build images
        run: docker compose -f docker-compose.yml build --no-cache

      - name: Run App
        run: |
          docker compose -f docker-compose.yml up  -d
          docker compose ps

      - name: Wait for service
        run: |
          while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{else if .State.Status}}{{print .State.Status}}{{end}}" "$(docker compose ps -q app)")"; do
            case $status in
              starting) sleep 1;;
              healthy) exit 0;;
              running) exit 0;;
              unhealthy)
                docker compose ps
                docker compose logs php-fpm
                exit 1
              ;;
            esac
          done
          exit 1

      - name: Check App
        run: |
          sleep 5
          HTTP_CODE=$(curl -ik -X GET 'http://localhost:8081/health-check' -o /dev/null -w '%{http_code}\n' -s)
          echo $HTTP_CODE
          if [ "$HTTP_CODE" = "200" ]; then
              exit 0
          fi
            docker compose ps
            docker compose logs 
          exit 1