name: build and test

on:
  push:
    branches:
      - release
      - master
env:
  APP_ENV: test
  HEROKU_ENABLE_DEPLOY: ${{secrets.HEROKU_ENABLE_DEPLOY}}
  APP_NAME: 'api-lead-suzuki-preprod'
  APP_ID: '1ead981478b4'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sets env vars
        run: |
          echo "APP_NAME=api-lead-suzuki-prod" >> $GITHUB_ENV
          echo "APP_ID=68d8046780cc" >> $GITHUB_ENV
        if: ${{ github.ref == 'refs/heads/master'}}

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/checkout@v4
      - name: Set Heroku Email
        shell: bash
        run: echo "##[set-output name=email;]$(git log -n 1 --pretty=format:%ae)"
        id: heroku_email

      - name: Deployment
        uses: akhileshns/heroku-deploy@v3.13.15
        env:
          APP_NAME: ${{ env.APP_NAME }}
          APP_ID: ${{ env.APP_ID }}
        if: ${{ env.HEROKU_ENABLE_DEPLOY == 'true' }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ env.APP_NAME }}
          heroku_email: ${{ steps.heroku_email.outputs.email }}
          branch: ${{ steps.extract_branch.outputs.branch }}
          healthcheck: 'https://${{ env.APP_NAME }}-${{ env.APP_ID }}.herokuapp.com/health-check'
          rollbackonhealthcheckfailed: true
          delay: 5
